### PR TITLE
style: review prompt made responsive

### PR DESCRIPTION
**Pull request by alinauroz**
This PR fixes https://github.com/cobudget/cobudget/issues/373

### CODE REVIEW

**Comment by aerugo** [comment]
This PR introduces a bug when I run it locally.

Steps to reproduce:

- Create collection
- Create a bucket
- Add guidelines to collection
- Enable review
- Go to bucket

Result:

Screenshot 2022-01-29 at 17 17 19

**Review by gustavlrsn — COMMENTED** [review]
Looks good, works much better on mobile. The one thing missing is to completely remove the gif in the corner and use the new button for both desktop and mobile, [per the last comment in the issue](https://github.com/cobudget/cobudget/issues/373#issuecomment-975427748)

**Comment by alinauroz** [comment]
> per the last comment in the issue

done

**Comment by gustavlrsn** [comment]
Great, merging

**Pull request merged**
