### PR TITLE
Only allow admins to create tags

### PR DESCRIPTION
**Pull request by Powersource**
Partially does https://github.com/Edgeryders-Participio/multi-dreams/issues/351

* [x] add mutation that admins can use to create tags
* [x] remove ability of addTag to create new tags
* [x] and update sidebar ui correspondingly
* [x] only display the tag sidebar if tags exist in the collection
* [x] move some files to ts

### CODE REVIEW

**Comment by gustavlrsn** [comment]
There are linting errors

**Comment by Powersource** [comment]
@gustavlrsn fixed

**Comment by Powersource** [comment]
note to self, this allows me to see a very messy diff compared to the deleted file, idk if it's too messy to help though `g diff -w HEAD:api/resolvers/index.ts ui/server/graphql/resolvers/index.ts`

**Comment by Powersource** [comment]
@gustavlrsn ready for review again

**Pull request merged**
